# Generated by Django 5.1.2 on 2025-01-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviewcopies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("student", "Student"), ("teacher", "Teacher")],
                max_length=10,
                null=True,
            ),
        ),
    ]
