# Generated by Django 5.1.2 on 2025-01-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviewcopies", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("admin", "Admin"),
                ],
                default="student",
                max_length=10,
            ),
        ),
    ]
